root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = ["serve"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", "db/queries/.*\\.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "sql", "templ"]
include_file = []
kill_delay = "500ms"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = [
    "mkdir -p public",
    "tailwindcss -i views/style.css -o public/style.css",
    "templ generate",
    "sqlc generate",
]
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
