**/*.go !"migrations/*.go" !"app/tmpl/**/*.go" app/tmpl/**/*.templ {
    prep: "
        # templ
        templ generate
    "
    daemon +sigint: "
        # redmage
        go run main.go serve
    "
}

tailwind.config.js app/tmpl/**/*.templ app/tmpl/style.css {
    prep: "
        # tailwindcss
        npx tailwindcss  --input app/tmpl/style.css --output public/style.css
    "
}
