**/*.go !"migrations/*.go" !"tmpl/**/*.go" tmpl/**/*.templ {
    prep: "
        # templ
        templ generate
    "
    daemon +sigint: "
        # redmage
        go run main.go serve
    "
}

tailwind.config.js tmpl/**/*.templ tmpl/style.css {
    prep: "
        # tailwindcss
        npx tailwindcss  --input tmpl/style.css --output public/style.css
    "
}
