**/*.go !"migrations/*.go" !"app/templates/**/*.go" app/templates/**/*.templ .env {
    prep: "
        # templ
        templ generate
    "
    daemon +sigint: "
        # redmage
        go run main.go serve
    "
}

tailwind.config.js app/templates/**/*.templ app/templates/style.css {
    prep: "
        # tailwindcss
        npx tailwindcss  --input app/templates/style.css --output public/style.css
    "
}
