on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: docker
    container:
      image: docker:26.1.2

    steps:
      - run: echo "Deploying version ${{ github.ref_name }}"
      - run: docker build -t git.tigor.web.id/tigor/redmage:${{ github.ref_name }} .
      - run: docker build -t git.tigor.web.id/tigor/redmage:latest .
      - run: docker push git.tigor.web.id/tigor/redmage:${{ github.ref_name }}
      - run: docker push git.tigor.web.id/tigor/redmage:latest
      - run: docker compose up -d
