# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push:
    runs-on: docker

    steps:
      - name: Login to Self Hosted Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.tigor.web.id
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Echo Build Version ${{ github.ref_name }}
        run: echo "Building version ${{ github.ref_name }}"
      - name: Docker Build
        run: docker build --push --build-arg REDMAGE_RUNTIME_VERSION=${{ github.ref_name }} -t git.tigor.web.id/tigor/redmage:${{ github.ref_name }} -t git.tigor.web.id/tigor/redmage:latest .
      #- name: Docker Push Image Version ${{ github.ref_name }}
      #  run: docker image push git.tigor.web.id/tigor/redmage:${{ github.ref_name }}
      #- name: Docker Push Image Latest
      #  run: docker image push git.tigor.web.id/tigor/redmage:latest
