# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push:
    runs-on: docker

    steps:
      - name: Login to Self Hosted Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.tigor.web.id
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Docker Build and Push to Forgejo Registry
        run: docker buildx build --push --build-arg REDMAGE_RUNTIME_VERSION=${{ github.ref_name }} -t git.tigor.web.id/${{secrets.DOCKER_USERNAME}}/redmage:${{ github.ref_name }} -t git.tigor.web.id/tigor/redmage:latest .
