POST http://localhost:8080/api/v1/devices HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Laptop",
    "slug": "laptop",
    "resolution_x": 2560,
    "resolution_y": 1440,
    "nsfw": 1,
    "aspect_ratio_tolerance": 0.2,
    "enable": 1,
    "min_x": 2560,
    "min_y": 1440
}
