POST http://localhost:8080/api/v1/devices HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Phone",
    "slug": "phone",
    "resolution_x": 1080,
    "resolution_y": 2400,
    "nsfw": 1,
    "aspect_ratio_tolerance": 0.2,
    "enable": 1,
    "min_x": 1080,
    "min_y": 2400
}
